# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.activate = QtWidgets.QPushButton(self.tab_3)
        self.activate.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.activate.setObjectName("activate")
        self.desactivate = QtWidgets.QPushButton(self.tab_3)
        self.desactivate.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.desactivate.setObjectName("desactivate")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 50, 161, 20))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")

        self.spending_add = QtWidgets.QPushButton(self.tab_4)
        self.spending_add.setGeometry(QtCore.QRect(110, 160, 75, 23))
        self.spending_add.setObjectName("spending_add")

        self.spending_add.clicked.connect(self.fn_add_spending)
        self.spending_description = QtWidgets.QLineEdit(self.tab_4)
        self.spending_description.setGeometry(QtCore.QRect(120, 100, 221, 20))
        self.spending_description.setObjectName("spending_description")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.spending_amount = QtWidgets.QLineEdit(self.tab_4)
        self.spending_amount.setGeometry(QtCore.QRect(120, 130, 221, 20))
        self.spending_amount.setObjectName("spending_amount")
        self.spending_category = QtWidgets.QComboBox(self.tab_4)
        self.spending_category.setGeometry(QtCore.QRect(120, 70, 221, 22))
        self.spending_category.setObjectName("spending_category")
        self.spending_category.addItem("")
        self.spending_category.setItemText(0, "")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_category.addItem("")
        self.spending_modify = QtWidgets.QPushButton(self.tab_4)
        self.spending_modify.setGeometry(QtCore.QRect(190, 160, 75, 23))
        self.spending_modify.setObjectName("spending_modify")
        self.spending_delete = QtWidgets.QPushButton(self.tab_4)
        self.spending_delete.setGeometry(QtCore.QRect(270, 160, 75, 23))
        self.spending_delete.setObjectName("spending_delete")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(420, 60, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(380, 70, 20, 331))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spending_warning = QtWidgets.QLabel(self.tab_4)
        self.spending_warning.setGeometry(QtCore.QRect(120, 180, 211, 31))
        self.spending_forward = QtWidgets.QPushButton(self.tab_4)
        self.spending_forward.setGeometry(QtCore.QRect(610, 380, 41, 23))
        self.spending_forward.setObjectName("spending_forward")
        self.spending_back = QtWidgets.QPushButton(self.tab_4)
        self.spending_back.setGeometry(QtCore.QRect(550, 380, 41, 23))
        self.spending_back.setObjectName("spending_back")
        self.spending_table = QtWidgets.QTableWidget(self.tab_4)
        self.spending_table.setGeometry(QtCore.QRect(420, 100, 391, 271))
        self.spending_table.setObjectName("spending_table")
        self.spending_table.setColumnCount(0)
        self.spending_table.setRowCount(0)
        self.spending_calendary = QtWidgets.QCalendarWidget(self.tab_4)
        self.spending_calendary.setGeometry(QtCore.QRect(30, 210, 331, 191))
        self.spending_calendary.setObjectName("spending_calendary")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 281, 31))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #####
        self.items = 0
        self.data = {}

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activate.setText(_translate("MainWindow", "Activar"))
        self.desactivate.setText(_translate("MainWindow", "Desactivar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.spending_add.setText(_translate("MainWindow", "Add"))
        self.label_2.setText(_translate("MainWindow", "Categoria"))
        self.label_3.setText(_translate("MainWindow", "Descripción"))
        self.label_4.setText(_translate("MainWindow", "Monto"))
        self.spending_category.setItemText(1, _translate("MainWindow", "Ropa"))
        self.spending_category.setItemText(2, _translate("MainWindow", "Viajes"))
        self.spending_category.setItemText(3, _translate("MainWindow", "Transporte"))
        self.spending_category.setItemText(4, _translate("MainWindow", "Comida"))
        self.spending_category.setItemText(5, _translate("MainWindow", "Salud"))
        self.spending_category.setItemText(6, _translate("MainWindow", "Entretenimiento"))
        self.spending_category.setItemText(7, _translate("MainWindow", "Salidas"))
        index = self.spending_category.findText("Ropa", QtCore.Qt.MatchFixedString)
        self.spending_category.setCurrentIndex(index)
        self.spending_modify.setText(_translate("MainWindow", "Modify"))
        self.spending_delete.setText(_translate("MainWindow", "Delete"))
        self.label_5.setText(_translate("MainWindow", "Agosto 2021"))
        self.spending_forward.setText(_translate("MainWindow", "--->"))
        self.spending_back.setText(_translate("MainWindow", "<--"))
        self.label_6.setText(_translate("MainWindow", "Agregar Gastos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))

    def fn_add_spending(self):
        """ Add new spending to the list """
        calendary = self.spending_calendary.selectedDate()
        calendary = f"{calendary.day()}/{calendary.month()}/{calendary.year()}"
        category = self.spending_category.currentText()
        description = self.spending_description.text()
        amount = self.spending_amount.text()

        if amount.isdigit():
            self.items += 1
            self.data[self.items] = [calendary,category,description,amount]
            self.spending_table.setRowCount(len(self.data))
            self.spending_table.setColumnCount(4)
            self.spending_table.setHorizontalHeaderLabels(["Fecha","Categoría","Descripción","Monto"])

            self.spending_warning.setText("")
            count_k, count_v = 0,0
            for k in self.data.keys():
                for v in self.data[k]:
                    #print(v,end="")
                    print(count_k,count_v,v,end="  ")
                    self.spending_table.setItem(count_k,count_v,QTableWidgetItem(v))
                    count_v += 1
                count_v = 0
                count_k += 1
                print()
        else:
            self.spending_warning.setText("Datos invalidos. Intenta de nuevo")

        self.spending_description.setText("")
        self.spending_amount.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
